# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

source /home/gerrza/.config/wal/templates/colors-hyprland.conf

$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show run


bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, D, exec, $menu

# Increase brightness
bind = , XF86MonBrightnessUp, exec, brightnessctl set 5%+

# Decrease brightness
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
